name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth_service
          - reservation-service
          - Seminaire-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for ${{ matrix.service }}
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: HadilXattia/${{ matrix.service }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1

    - name: Deploy Auth Service
      run: |
        helm upgrade --install auth-service ./helm-auth-service \
          --set image.repository=HadilXattia/auth_service \
          --set image.tag=latest

    - name: Deploy Reservation Service
      run: |
        helm upgrade --install reservation-service ./helm-reservation-service \
          --set image.repository=HadilXattia/reservation-service \
          --set image.tag=latest

    - name: Deploy Seminaire Service
      run: |
        helm upgrade --install seminaire-service ./helm-seminaire-service \
          --set image.repository=HadilXattia/Seminaire-service \
          --set image.tag=latest
